# Generated by Django 4.0.4 on 2022-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertransaction_remove_images_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransaction',
            name='images_left',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='images_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
