# Generated by Django 4.0.4 on 2022-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_images_image_updated_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updated_image',
            name='updated_image',
            field=models.CharField(max_length=400),
        ),
    ]
