# Generated by Django 4.0.4 on 2022-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_updated_image_updated_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='userdata',
            name='images_left',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='uploads_till_now',
            field=models.IntegerField(default=0),
        ),
    ]
