# Generated by Django 4.0.4 on 2022-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_created_at_usertransaction_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
